version: '3'

services:
    async-download-service:
        image: python:3.7
        ports:
            - "8080:8080"
        volumes:
            - ./:/app
        working_dir: /app
        command: ['./entrypoint.sh']

