version: '3'

services:
    async-download-service:
        build: .
        ports:
            - "8080:8080"
        working_dir: /app
        volumes:
            - ./src:/app
            - ./test_photos:/photos
        command: python server.py

