version: '3'

services:
    async-download-service:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./test_photos:/photos
        command: ['./entrypoint.sh']

